spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/core
    username: postgres
    password: 12345
  jpa:
    show-sql: false

springdoc:
  swagger-ui:
    path: core/doc/swagger-ui.html

server:
  servlet:
    context-path: /api/v1/core
